### ISSUE TITLE
Backend | Project Structure checked in GIT Hub

### ISSUE THREAD

**Issue by shubhamknoldus** [shubhamknoldus/knol-bucks-spring#1]
As a Product Owner, I would like to have the Project Structure checked in GIT Hub. The project should use the Maven Build Tool.

Acceptance Criteria

- [x] All the dependencies should be included in Pom.xml
- [x] Set up Spring Booot Web Flux Project Structure.
- [x] Checkin in GIT HUB.
- [x] Use Maven Build Tools.
- [x] Add all Spring WebFlux Dependencies.

**Comment by shubhamknoldus** [comment]
@vinishasharma  i am adding you as an assignee as well as you were doing the refactoring for the final project structure

**Comment by vinishasharma** [comment]
sure @shubhamknoldus 
I don't think we need to make here a web client specifically to just call a hello world message response. 
will be updating the code in my PR. We can use Mono and Flux once we will work with DB.
